### ISSUE TITLE
As a user, I would like the data to be accurate, because misinformation can be more dangerous than ignorance.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#37]
closed with commit 2c825532273ef40c1dfb9e8250e37e1a91afc00a
Ensemble network created

**Comment by JMBeresford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/37?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @gdochoa @sedwardsmarsh
