### ISSUE TITLE
As a user, I want the data to be relevant to the purpose of the experience.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#39]
Preprocess data etc

closed with commit 07c030f26106649079963be907d5bf1090d468b6

**Comment by JMBeresford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/39?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @gdochoa @sedwardsmarsh
