### ISSUE TITLE
As a user, I want to be able to navigate the UI/experience intuitively, because otherwise I may miss information and/or get frustrated.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#41]
Implement camera movement and restraints

**Comment by JMBeresford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/41?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @gdochoa @sedwardsmarsh
