### ISSUE TITLE
As a user, I would like to see a proper domain name, because it makes me feel like the information there is more reputable.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#42]
Get a proper domain name such as deforestationdetector.com

**Comment by JMBeresford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/42?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @gdochoa @sedwardsmarsh

**Comment by sedwardsmarsh** [comment]
deforestationdetector.ml
