### ISSUE TITLE
As a user, I want to be able to input an image and get a prediction on it.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#43]

**Comment by JMBeresford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/43?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @gdochoa @sedwardsmarsh
