### ISSUE TITLE
As a user, I would like calls to action that can lead me to ways of contributing to the efforts against deforestation.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#44]
Find actionable resources to provide the users access to. Display these resources in the information page.

**Comment by JMBeresford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/44?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @gdochoa @sedwardsmarsh
