### ISSUE TITLE
Optimize model checkpointing - cache in RAM

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#48]
Idk if checkpoints does this, but I remember checkpointing adding a few seconds onto a normal training routine when writing the weights to disk. Maybe there's a way that we can keep the best weights in motherboard RAM, not gpu RAM, until all epochs have completed.

**Comment by Donovanphenry** [comment]
Use the cache to determine if a model should be stored to save time.
