### ISSUE TITLE
Create an arg parser

### ISSUE THREAD

**Issue by Donovanphenry** [Deforestation-Detector/SCAI-Net#61]

**Comment by Donovanphenry** [comment]
Implement the following arguments

`
-d: debugger mode. Print variables`
`-v: Verbose mode. Display loss graphs, precision graphs, confusion matrices etc`
`-t: Training mode. Train the next N models that follow this flag.`
`-l: Load mode. Load the next N models that follow this flag from the working directory.`
`-e: Evaluate model. Evaluate the next N models that follow this flag.`
`-ts: Train and save mode. Train the next N models that follow this flag and save each.`

**Comment by sedwardsmarsh** [comment]
when using the `-l` flag, the user should list the names of the models they want to train.
