### ISSUE TITLE
As a user, I would like clear/intuitive indication of how to navigate unique elements of the experience, because otherwise I might get lost or miss content.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#65]

**Comment by geoochoa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/65?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @JMBeresford @sedwardsmarsh
