### ISSUE TITLE
As a user, I would like to see an example of the satellite images used for the 3D experience while I am investigating it.

### ISSUE THREAD

**Issue by sedwardsmarsh** [Deforestation-Detector/SCAI-Net#66]

**Comment by geoochoa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/SCAI-Net/66?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @JMBeresford @sedwardsmarsh
